# Generated by Django 5.2.16 on 2026-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_endpoints', models.JSONField(blank=True, default=list, help_text='Leave empty to allow all endpoints. Example: ["detect", "liveness", "compare", "health"]')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
